[package]
name = "harmonizer"
version = "0.1.0"
authors = ["Apollo Developers <opensource@apollographql.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.35"
deno_core = "0.73.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.60"
thiserror = "1.0.23"

[dev-dependencies]
insta = "1.5.2"